import { Product } from "@/types/Product";

export const PRODUCTS: Product[] = [
  {
    name: "Red Running Shoes",
    description: "Perfect for running and everyday use.",
    price: 79.99,
    image: "/images/shoes/product/r1.webp",
    alt: "Red Running Shoes",
    category: "Running",
    gender: "Unisex",
    details: {
      material: "Breathable mesh",
      sole: "Rubber sole with high traction",
      weight: "Lightweight design, 200g per shoe",
      colors: ["Red", "Black"],
      sizes: ["7", "8", "9", "10", "11"],
    },
  },
  {
    name: "Blue Sports Shoes",
    description: "Lightweight and stylish sportswear.",
    price: 89.99,
    image: "/images/shoes/product/b1.webp",
    alt: "Blue Sports Shoes",
    category: "Sportswear",
    gender: "Men",
    details: {
      material: "Synthetic upper with cushioning",
      sole: "Shock-absorbing midsole",
      weight: "Medium weight, 250g per shoe",
      colors: ["Blue", "White"],
      sizes: ["6", "7", "8", "9", "10"],
    },
  },
  {
    name: "Black Casual Shoes",
    description: "Comfortable and perfect for outings.",
    price: 69.99,
    image: "/images/shoes/product/bs1.webp",
    alt: "Black Casual Shoes",
    category: "Casual",
    gender: "Unisex",
    details: {
      material: "Premium leather",
      sole: "Soft padded insole for comfort",
      weight: "Lightweight, 220g per shoe",
      colors: ["Black", "Brown"],
      sizes: ["6", "7", "8", "9", "10", "11"],
    },
  },
  {
    name: "Green Hiking Boots",
    description: "Durable and perfect for all terrains.",
    price: 99.99,
    image: "/images/shoes/product/g1.webp",
    alt: "Green Hiking Boots",
    category: "Hiking",
    gender: "Men",
    details: {
      material: "Waterproof fabric with reinforced stitching",
      sole: "Anti-slip rugged outsole",
      weight: "Heavy-duty, 400g per shoe",
      colors: ["Green", "Gray"],
      sizes: ["8", "9", "10", "11", "12"],
    },
  },
  {
    name: "White Sneakers",
    description: "Minimalist sneakers perfect for casual wear and comfort.",
    price: 89.99,
    image: "/images/shoes/product/white-sneakers.webp",
    alt: "White Sneakers",
    category: "Casual",
    gender: "Unisex",
    details: {
      material: "Breathable canvas",
      sole: "Cushioned foam sole",
      weight: "300g per shoe",
      colors: ["White", "Grey"],
      sizes: ["6", "7", "8", "9", "10", "11"],
    },
  },
  {
    name: "Yellow Running Shoes",
    description:
      "Vibrant and lightweight running shoes for optimal performance.",
    price: 84.99,
    image: "/images/shoes/product/yellow-running-shoes.webp",
    alt: "Yellow Running Shoes",
    category: "Running",
    gender: "Women",
    details: {
      material: "Knitted fabric with breathable technology",
      sole: "Durable EVA foam sole",
      weight: "Ultra-lightweight, 210g per shoe",
      colors: ["Yellow", "Black"],
      sizes: ["6", "7", "8", "9", "10"],
    },
  },
  {
    name: "Brown Leather Boots",
    description: "Elegant leather boots ideal for casual and formal wear.",
    price: 129.99,
    image: "/images/shoes/product/brown-leather-boots.webp",
    alt: "Brown Leather Boots",
    category: "Boots",
    gender: "Men",
    details: {
      material: "Premium genuine leather",
      sole: "Non-slip rubber sole",
      weight: "Medium weight, 500g per shoe",
      colors: ["Brown", "Tan"],
      sizes: ["8", "9", "10", "11", "12"],
    },
  },
  {
    name: "Pink Sports Shoes",
    description: "Stylish sports shoes with excellent cushioning and support.",
    price: 74.99,
    image: "/images/shoes/product/pink-sports-shoes.webp",
    alt: "Pink Sports Shoes",
    category: "Sportswear",
    gender: "Women",
    details: {
      material: "Synthetic upper with breathable mesh",
      sole: "Cushioned sole for impact absorption",
      weight: "Lightweight, 220g per shoe",
      colors: ["Pink", "White"],
      sizes: ["6", "7", "8", "9"],
    },
  },
];
